project_id = "ezjtheshclmruzlgwyfa"

[functions.delete-user]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-daily-reminder]
verify_jwt = false

[functions.sync-monthly-check]
verify_jwt = false

[functions.notify-video-correction]
verify_jwt = false

[functions.send-quiz-email]
verify_jwt = false

[functions.check-absences]
verify_jwt = false

[functions.notify-interaction]
verify_jwt = false
